name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get dependencies and build
      run: |
        yarn install
        yarn build
        zip -r dist.zip dist
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

    # - name: Draft Release
    #   uses: softprops/action-gh-release@v1
    #   if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
    #   with:
    #     files: dist.zip
    #     draft: true
